# version
version: "3.8"

#services
services:
  #mongo
  usermongodb:
    image: "mongo"

    ports:
      - "27017:27017"
    volumes:
      - /Users/lphan/Desktop/data/userdata:/data/db/

    networks:
      - microapps


  devicemongodb:
    image: "mongo"

    ports:
      - "27018:27017"

    volumes:
      - /Users/lphan/Desktop/data/devicedata:/data/db/

    networks:
      - microapps

  userservice:
    image: "userservice"
    build: ./user-service
#    ports:
#      - 9000:9000
    depends_on:
      - usermongodb

    environment:
      PORT: 9000
      MONGO_URL: "mongodb://usermongodb:27017/users"

    networks:
      - microapps

  deviceservice:
    image: "deviceservice"
    build: ./device-service
#    ports:
#      - 9100:9100
    depends_on:
      - devicemongodb

    environment:
      PORT: 9100
      MONGO_URL: "mongodb://devicemongodb:27017/devices"

    networks:
      - microapps

  ui:
    image: "uiservice"

    build: ./ui

    ports:
      - 80:80

    depends_on:
      - userservice
      - deviceservice

    environment:
      USER_ENDPOINT: http://userservice:9000/api/users
      DEVICE_ENDPOINT: http://deviceservice:9100/api/devices

    networks:
      - microapps

networks:
  microapps:
