# version
version: "3.8"

#services
services:
  #mongo
  usermongodb:
    image: "mongo"

    ports:
      - "27017:27017"
    volumes:
      - data:/data/db

    networks:
      - microapps


  devicemongodb:
    image: "mongo"

    ports:
      - "27018:27017"

    volumes:
      - data:/data/db

    networks:
      - microapps

  userservice:
    image: "userservice"
    build: ./user-service
#    ports:
#      - 8080:9000
    depends_on:
      - usermongodb

    environment:
      PORT: 9000
      MONGO_URL: "mongodb://usermongodb:27017/users"

    networks:
      - microapps

  deviceservice:
    image: "deviceservice"
    build: ./device-service
#    ports:
#      - 8090:9100
    depends_on:
      - usermongodb

    environment:
      PORT: 9100
      MONGO_URL: "mongodb://devicemongodb:27017/devices"

    networks:
      - microapps

  ui:
    image: "uiservice"

    build: ./ui

    ports:
      - 80:80

    depends_on:
      - userservice
      - deviceservice

    environment:
      NGINX_HOST: http://localhost
      NGINX_PORT: 80

    networks:
      - microapps

volumes:
  data:

networks:
  microapps: