apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: device-mongo-pvc
  namespace: microservicesapp
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 256Mi
---
apiVersion: v1
kind: Service
metadata:
  name: devicemongo
  namespace: microservicesapp
spec:
  selector:
    app: devicemongo
  ports:
    - port: 27017
      targetPort: 27017
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: devicemongo
  namespace: microservicesapp
spec:
  replicas: 1
  selector:
    matchLabels:
      app: devicemongo
  template:
    metadata:
      labels:
        app: devicemongo
    spec:
      containers:
        - name: mongo
          image: mongo
          ports:
            - containerPort: 27017
          volumeMounts:
            - name: storage
              mountPath: /data/db

      volumes:
        - name: storage
          persistentVolumeClaim:
            claimName: device-mongo-pvc