apiVersion: v1
kind: Service
metadata:
  name: deviceservice
  namespace: microservicesapp
spec:
  selector:
    app: deviceservice
  ports:
    - port: 9100
      targetPort: 9100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deviceservice
  namespace: microservicesapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deviceservice
  template:
    metadata:
      labels:
        app: deviceservice
    spec:
      containers:
        - name: deviceservice
          image: deviceservice
          ports:
            - containerPort: 9100
          env:
            - name: PORT
              value: "9100"
            - name: MONGO_URL
              value: 'mongodb://devicemongo:27017/devices'
