apiVersion: v1
kind: Service
metadata:
  name: ui
  namespace: microservicesapp
spec:
  selector:
    app: ui
  ports:
    - port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ui
  namespace: microservicesapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: ui
  template:
    metadata:
      labels:
        app: ui
    spec:
      containers:
        - name: client
          image: uiservice
          ports:
            - containerPort: 80
