apiVersion: v1
kind: Service
metadata:
  name: userservice
  namespace: microservicesapp
spec:
  selector:
    app: userservice
  ports:
    - port: 9000
      targetPort: 9000
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: userservice
  namespace: microservicesapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: userservice
  template:
    metadata:
      labels:
        app: userservice
    spec:
      containers:
        - name: userservice
          image: userservice
          ports:
            - containerPort: 9000
          env:
            - name: PORT
              value: "9000"
            - name: MONGO_URL
              value: "mongodb://usermongo:27017/users"
