apiVersion: v1
kind: Service
metadata:
  name: deviceservice
  namespace: tiltapp
spec:
  selector:
    app: deviceservice
  ports:
    - port: 9100
      targetPort: 9100
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: deviceservice
  namespace: tiltapp
spec:
  replicas: 2
  selector:
    matchLabels:
      app: deviceservice
  template:
    metadata:
      labels:
        app: deviceservice
    spec:
      containers:
        - name: deviceservice
          image: deviceservice
          ports:
            - containerPort: 9100
          envFrom:
            - configMapRef: # referencing the ConfigMap
                name: device-config # name of the ConfigMap
          env:
            - name: PORT
              value: "9100"
